version: "3.7"
services:
  node1:
    build: ansible-nodes/
    container_name: node1
    ports:
      - "22"
      - "25"
      - "443"
      - "80"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs: /run
    healthcheck:
        test: ["CMD", "systemctl", "is-active", "sshd.service"]
        interval: 30s
        timeout: 10s
        retries: 5
    privileged: true
  node2:
    build: ansible-nodes/
    container_name: node2
    ports:
      - "22"
      - "25"
      - "443"
      - "80"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs: /run
    healthcheck:
        test: ["CMD", "systemctl", "is-active", "sshd.service"]
        interval: 30s
        timeout: 10s
        retries: 5
    privileged: true
  ansible:
    container_name: ansible
    build: ansible-controller/
    volumes:
      - config-data:/home/rhce
    depends_on:
      - node1
      - node2
    privileged: false
volumes:
  config-data:
