name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug PWD 
        run: echo $PWD && ls -lart .
      - name: generate needed ssh-key pair and move it to the right folder
        run: ssh-keygen -f $PWD/id_ra -q -N "" && mv $PWD/id_rsa ansible-controller && mv $PWD/id_rsa.pub ansible-nodes
      - name: Build the stack
        run: docker-compose up -d
      - name: Test ansible ping command as ansible user
        run: docker-compose run ansible ansible nodes -i inventory -m ping
      - name: Test ansible ping command as ansible user and become root
        run: docker-compose run ansible ansible nodes -i inventory -m ping --become